apiVersion: apps/v1
kind: Deployment

metadata:
  name: loan-default-api
  namespace: staging

spec:
  replicas: 1

  selector:
    matchLabels:
      app: loan-default-api

  template:
    metadata:
      labels:
        app: loan-default-api

    spec:
      imagePullSecrets:
        - name: artifact-registry-secret

      containers:
        - name: loan-default-api

          image: europe-west1-docker.pkg.dev/valid-design-385517/mlops-repo/loan-default-api:a46a0b3e3bd57030be478670bfbcc13eba2ffdb1

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: GCP_BUCKET_NAME
              value: "bigdata-mlop-bucket"