apiVersion: apps/v1
kind: Deployment

metadata:
  name: loan-default-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: loan-default-api

  template:
    metadata:
      labels:
        app: loan-default-api

    spec:
      imagePullSecrets:
        - name: artifact-registry-secret

      containers:
        - name: loan-default-api

          image: europe-west1-docker.pkg.dev/valid-design-385517/mlops-repo/loan-default-api:a40e1d45989c6c07d3b8b5d96fe7a1021df08583

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: GCP_BUCKET_NAME
              value: "bigdata-mlop-bucket"