apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loan-default-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Zeeshanch124/bigdata-arch-mlops-end-to-end-pipeline
    targetRevision: main
    path: kubernetes/production

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true