name: CI-CD-Orchestrator

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'

permissions:
  contents: write

jobs:

  changes:
    runs-on: ubuntu-latest

    outputs:
      monitoring: ${{ steps.filter.outputs.monitoring }}
      training: ${{ steps.filter.outputs.training }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: filter

        with:
          filters: |

            monitoring:
              - 'api/**'
              - 'src/monitoring/**'
              - 'Dockerfile'
              - 'kubernetes/**'

            training:
              - 'src/models/**'
              - 'src/data_pipeline/**'
              - 'training/**'
              - 'data/**'

  ci:
    needs: changes
    uses: ./.github/workflows/ci.yml

  ingestion:
    needs: [changes, ci]

    if: needs.changes.outputs.training == 'true'

    uses: ./.github/workflows/ingestion.yml

    secrets: inherit

  training:
    needs: [changes, ingestion]

    if: needs.changes.outputs.training == 'true'

    uses: ./.github/workflows/training.yml

    secrets: inherit

  deploy-staging-api:
    if: |
      github.ref == 'refs/heads/develop' &&
      needs.changes.outputs.monitoring == 'true'

    needs:
      - changes
      - ci

    uses: ./.github/workflows/deploy.yml

    with:
      environment: staging
      manifest_path: kubernetes/staging/deployment.yaml

    secrets: inherit

  deploy-staging-model:
    if: |
      github.ref == 'refs/heads/develop' &&
      needs.changes.outputs.training == 'true'

    needs:
      - changes
      - ci
      - ingestion
      - training
       

    uses: ./.github/workflows/deploy.yml

    with:
      environment: staging
      manifest_path: kubernetes/staging/deployment.yaml

    secrets: inherit

  deploy-production-api:
    if: |
      github.ref == 'refs/heads/main' &&
      needs.changes.outputs.monitoring == 'true'

    needs:
      - changes
      - ci

    uses: ./.github/workflows/deploy.yml

    with:
      environment: staging
      manifest_path: kubernetes/production/deployment.yaml

    secrets: inherit

  deploy-production:
    if: |
      github.ref == 'refs/heads/main' &&
      needs.changes.outputs.training == 'true'

    needs:
      - changes
      - ci
      - ingestion
      - training

    uses: ./.github/workflows/deploy.yml

    with:
      environment: production
      manifest_path: kubernetes/production/deployment.yaml

    secrets: inherit