name: CI-CD-Orchestrator

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'

permissions:
  contents: write

jobs:

  ci:
    uses: ./.github/workflows/ci.yml

  ingestion:
    needs: ci
    uses: ./.github/workflows/ingestion.yml
    secrets: inherit

  training:
    needs: ingestion
    uses: ./.github/workflows/training.yml
    secrets: inherit

  deploy-staging:
    if: github.ref == 'refs/heads/develop'

    needs: training

    uses: ./.github/workflows/deploy.yml

    with:
      environment: staging
      manifest_path: kubernetes/staging/deployment.yaml

    secrets: inherit

  deploy-production:
    if: github.ref == 'refs/heads/main'

    needs: training

    uses: ./.github/workflows/deploy.yml

    with:
      environment: production
      manifest_path: kubernetes/production/deployment.yaml

    secrets: inherit