name: CI Pipeline

on:
  workflow_call:
      
  pull_request:
    branches:
      - main

jobs:
  test-and-validate:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Project
        run: |
          pip install -e .

      - name: Run Unit Tests
        run: |
          pytest