name: CI-CD-Pipeline

on:
  push:
    branches:
      - feature/training-pipeline

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Verify Artifact Registry Access
        run: |
          gcloud config list
          gcloud artifacts repositories list


      - name: Build Docker Image
        run: |
          docker build -t europe-west1-docker.pkg.dev/valid-design-385517/mlops-repo/loan-default-api:${{ github.sha }} .

      - name: Test Docker Push Auth
        run: |
          gcloud auth print-access-token

      - name: Push Docker Image
        run: |
          docker push europe-west1-docker.pkg.dev/valid-design-385517/mlops-repo/loan-default-api:${{ github.sha }}

      - name: Update Kubernetes Manifest
        run: |
          sed -i "s|image: .*|image: europe-west1-docker.pkg.dev/valid-design-385517/mlops-repo/loan-default-api:${{ github.sha }}|g" kubernetes/deployment.yaml

      - name: Commit Updated Manifest
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git add kubernetes/deployment.yaml

          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes"

          git push origin feature/training-pipeline