name: Model Training Pipeline

on:
  push:
    paths:
      - 'src/models/**'
      - 'src/data_pipeline/**'
  workflow_call:
  
jobs:
  training:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}

      - name: Run Model Training
        run: |
          python src/models/train.py